### ISSUE TITLE
compatibility with other mods

### ISSUE THREAD

**Issue by peow** [MediumDifficulty/ElytraTime#1]
Could you add compatibility with mods that add the ability to use Elytra in the Trinkets Cape Slot? like the Elytra Slot mod and Elytra Trinket mod?
![image](https://github.com/MediumDifficulty/ElytraTime/assets/105888751/e32d894d-3764-457b-9712-9e753ca8dd11)

**Comment by MediumDifficulty** [comment]
From the little research I have done, it looks like both mods that you mentioned use the Trinkets API. I don't have any experience with it but I can certainly give it a try.

**Comment by MediumDifficulty** [comment]
Ok, I have it working... I assume with trinkets that 1. you can only have one elytra equipped and 2. that elytra is the one used for flying.
