### ISSUE TITLE
Using f3+f4 to change gamemodes 

### ISSUE THREAD

**Issue by steve-the-player** [MediumDifficulty/ElytraTime#3]
I'm in a creative world, but I'll frequently switch to spectator, and I use the f3 shortcut where you hold down f3 and tap f4 to change gamemodes. This also brings up the "you are not wearing any elytra!" warning in chat every time. Could we make it ignore the f3f4 shortcut?

**Comment by MediumDifficulty** [comment]
Interesting... I would think that the default keybinding system would take care of this. An obvious solution to this is that I could just change the default keybind from f4.

**Comment by MediumDifficulty** [comment]
> if im not incorrect, this isnt a Elytra Time behavior, this happened to me because of a mod called Debug Keybind, check if you have it, and if yes, update it to stop this

Can confirm 👍
