### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by Legendmanj** [MediumDifficulty/ElytraTime#5]
1.21 please (;

seems like one of the best improvements mod regarding the client side

**Comment by MediumDifficulty** [comment]
I'm currently waiting for Trinkets to be updated.

https://github.com/emilyploszaj/trinkets/issues/321

As soon as there's a release I don't see why I can't update this :)

**Comment by Legendmanj** [comment]
> I'm currently waiting for Trinkets to be updated.
> 
> [emilyploszaj/trinkets#321](https://github.com/emilyploszaj/trinkets/issues/321)
> 
> As soon as there's a release I don't see why I can't update this :)

gg

**Comment by MediumDifficulty** [comment]
Should be done
